name: flutter_cleaner
description: A sample command-line application.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  args: ^2.3.0 #解析命令行参数


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

# 配置标识为包的可执行文件
executables:
  flutter_cleaner: flutter_cleaner
