name: Dart Package CI/CD

on:
  push:
    tags:
      - 'v*'  # 只有当推送 v* 标签时，才会触发发布
    # branches:
    #   - main # default branch

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Dependencies
        run: dart pub get

      - name: Run Tests
        run: dart test

  publish:
    name: Publish to pub.dev
    runs-on: ubuntu-latest
    needs: test  # 只有测试通过后才会执行发布
    if: startsWith(github.ref, 'refs/tags/v')  # 仅在 v* 标签时发布

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Dependencies
        run: dart pub get

      - name: Publish Package
        env:
          PUB_CREDENTIALS: ${{ secrets.DART_PUB_CREDENTIALS }}
        run: |
          echo "$PUB_CREDENTIALS" > ~/.pub-cache/credentials.json
          dart pub publish --force
